### ISSUE TITLE
login.microsoftonline.com login.live.com

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#27]
This domain is for logging into Microsoft or O365 :)
 False positive

**Comment by p1r473** [comment]
I am going to stop using spy adblock list, way too many false positives :)

**Comment by muxcc** [comment]
[spy.hosts](https://github.com/muxcc/AdsBlockLists/blob/master/spy.hosts) - This is an update to the aggregated blacklist and Microsoft telemetry
