### ISSUE TITLE
substrate.office.com

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#28]
substrate.office.com is a CNAME for outlook.office.com
Blocking this domain is breaking Outlook on my phone

**Comment by p1r473** [comment]
I am going to stop using spy adblock list, way too many false positives :)

**Comment by muxcc** [comment]
[spy.hosts](https://github.com/muxcc/AdsBlockLists/blob/master/spy.hosts) - This is an update to the aggregated blacklist and Microsoft telemetry
--
you can not use, your right..
