### ISSUE TITLE
dns.msftncsi.com

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#3]
This is the connectivity check for Microsoft to see if youre online
This is not a malicious or ad related domain
I believe this is a flase positive
Thanks

**Comment by muxcc** [comment]
Yes, this is a false positive. You're right.
[Network Connectivity Status Indicator](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766017(v=ws.10)?redirectedfrom=MSDN)
-
fix
