### ISSUE TITLE
fe2cr.update.microsoft.com ctldl.windowsupdate.com fe3.delivery.mp.microsoft.com)

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#30]
Hi,
This is breaking Microsoft Updates :)

**Comment by p1r473** [comment]
I am going to stop using spy adblock list, way too many false positives :)

**Comment by muxcc** [comment]
[spy.hosts](https://github.com/muxcc/AdsBlockLists/blob/master/spy.hosts) - This is an update to the aggregated blacklist and Microsoft telemetry
--
you can not use, your right..
