### ISSUE TITLE
windows.msn.com assets.msn.com

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#31]
This is breaking Windows 11 Start Menu :)
![image](https://user-images.githubusercontent.com/9235633/162641601-e299c004-8b37-4360-9555-9c245a9a01f3.png)

**Comment by p1r473** [comment]
I am going to stop using spy adblock list, way too many false positives :)

**Comment by muxcc** [comment]
[spy.hosts](https://github.com/muxcc/AdsBlockLists/blob/master/spy.hosts) - This is an update to the aggregated blacklist and Microsoft telemetry
--
you can not use, your right..
