### ISSUE TITLE
Public-api.wordpress.com

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#36]
wordpress API, not malicious

**Comment by p1r473** [comment]
@muxcc

**Comment by muxcc** [comment]
it's not on the list

**Comment by p1r473** [comment]
![image](https://user-images.githubusercontent.com/9235633/212796435-6ffe171d-a0fa-4848-9fd5-d44df475e6ab.png)
@muxcc

**Comment by muxcc** [comment]
case insensitive
`Public-api.wordpress.com`

fix, done
