### ISSUE TITLE
Break Windows Updates 

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#5]
Your spy.hosts file is absolutely filled with Windows Updates domains
It's not all spy domains but a lot of good stuff too...

**Comment by p1r473** [comment]
I'm just going to stop using the spy list, it's got way too many false positive

**Comment by p1r473** [comment]
fe3.delivery.mp.microsoft.com is breaking windows updates in aumm.hosts

**Comment by muxcc** [comment]
Thanks! corrected..
The fact is that these domains are collected by hand for a long time on various clients, so there can be a lot of false positives.
There is a whitelist in pi-hole, it can be used as a temporary workaround.

**Comment by p1r473** [comment]
Thanks, I am always whitelisting on my end, but I report them to you in case other people use this list

**Comment by muxcc** [comment]
Thank you very much!
