### ISSUE TITLE
Break Microsoft teams

### ISSUE THREAD

**Issue by p1r473** [muxcc/AdsBlockLists#6]
This hosts teams static files
statics.teams.cdn.live.net
teams.live.com

**Comment by p1r473** [comment]
I'm just going to stop using the spy list, it's got way too many false positive

**Comment by muxcc** [comment]
Yes, you better not use it, because Microsoft has very strict rules due to their ubiquitous telemetry.

**Comment by muxcc** [comment]
added to whitelist
